<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="jakarta.tags.core" prefix="c" %>
<%@ taglib uri="jakarta.tags.functions" prefix="fn" %>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Forensafe – Overdue Alerts</title>
<link rel="stylesheet" href="<%= request.getContextPath() %>/css/style.css">
</head>
<body>
<%@ include file="shared/sidebar.jsp" %>

<div class="main-content">
  <div class="page-body">

    <c:if test="${not empty error}">
      <div class="alert alert-danger">${error}</div>
    </c:if>

    <div class="page-header">
      <div>
        <div class="page-title">OVERDUE <span>ALERTS</span></div>
        <div class="page-subtitle">// EVIDENCE STUCK IN LAB &mdash; CURSOR AUDIT REPORT</div>
      </div>
      <a href="<%= request.getContextPath() %>/overdue" class="btn btn-cyan">&#8635; REFRESH</a>
    </div>

    <div class="alert alert-info" style="margin-bottom:24px;font-size:11px;line-height:1.8">
      &#9654; Results generated by MySQL cursor:
      <strong style="color:var(--accent)">CALL sp_cursor_overdue_evidence()</strong>
      &mdash; Flags <strong>current_status = 'In Lab'</strong> evidence with no
      <strong>CUSTODY_TRANSFER</strong> activity for &gt; 7 days.
    </div>

    <div class="stats-grid" style="grid-template-columns:repeat(4,1fr);margin-bottom:28px">
      <div class="stat-card c3">
        <div class="stat-icon">&#9888;</div>
        <div class="stat-value" style="color:var(--warn)">${totalOverdue}</div>
        <div class="stat-label">Total Flagged</div>
        <div class="stat-meta">Evidence items overdue</div>
      </div>
      <div class="stat-card c4">
        <div class="stat-icon">&#128308;</div>
        <div class="stat-value" style="color:var(--danger)">${criticalCount}</div>
        <div class="stat-label">Critical</div>
        <div class="stat-meta">Stuck &gt; 30 days</div>
      </div>
      <div class="stat-card c3">
        <div class="stat-icon">&#128993;</div>
        <div class="stat-value" style="color:var(--warn)">${warningCount}</div>
        <div class="stat-label">Warning</div>
        <div class="stat-meta">Stuck 14&ndash;30 days</div>
      </div>
      <div class="stat-card c2">
        <div class="stat-icon">&#128994;</div>
        <div class="stat-value" style="color:var(--accent2)">${noticeCount}</div>
        <div class="stat-label">Notice</div>
        <div class="stat-meta">Stuck 7&ndash;14 days</div>
      </div>
    </div>

    <div class="card">
      <div class="card-header">
        <span class="card-title">FLAGGED EVIDENCE ITEMS</span>
        <span style="font-family:'Share Tech Mono',monospace;font-size:11px;color:var(--text-muted)">
          Sorted by days stuck &darr; &nbsp;|&nbsp; ${fn:length(overdueItems)} item(s)
        </span>
      </div>
      <div class="table-container">
        <table>
          <thead>
            <tr>
              <th>Evidence ID</th>
              <th>Type</th>
              <th>Case ID</th>
              <th>Days Stuck</th>
              <th>Last Movement</th>
              <th>Alert Level</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <c:choose>
              <c:when test="${empty overdueItems}">
                <tr><td colspan="7" style="text-align:center;padding:44px;font-family:'Share Tech Mono',monospace;font-size:12px;color:var(--accent2)">
                  &#10003; No overdue evidence. All lab items are within the 7-day threshold.
                </td></tr>
              </c:when>
              <c:otherwise>
                <c:forEach var="item" items="${overdueItems}">
                  <tr>
                    <td><span class="evidence-id-badge">${item.evidenceId}</span></td>
                    <td>${item.evidenceType}</td>
                    <td class="mono">${item.caseId}</td>
                    <td>
                      <c:choose>
                        <c:when test="${item.alertLevel == 'CRITICAL'}">
                          <span style="font-family:'Rajdhani',sans-serif;font-weight:700;font-size:24px;color:var(--danger)">${item.daysStuck}</span>
                        </c:when>
                        <c:when test="${item.alertLevel == 'WARNING'}">
                          <span style="font-family:'Rajdhani',sans-serif;font-weight:700;font-size:24px;color:var(--warn)">${item.daysStuck}</span>
                        </c:when>
                        <c:otherwise>
                          <span style="font-family:'Rajdhani',sans-serif;font-weight:700;font-size:24px;color:var(--accent2)">${item.daysStuck}</span>
                        </c:otherwise>
                      </c:choose>
                      <span style="font-size:11px;color:var(--text-muted)"> days</span>
                    </td>
                    <td style="font-family:'Share Tech Mono',monospace;font-size:11px;color:var(--text-secondary)">${item.lastMovement}</td>
                    <td>
                      <c:choose>
                        <c:when test="${item.alertLevel == 'CRITICAL'}"><span class="badge badge-critical">&#9888; CRITICAL</span></c:when>
                        <c:when test="${item.alertLevel == 'WARNING'}"><span class="badge badge-warning">&#9651; WARNING</span></c:when>
                        <c:otherwise><span class="badge badge-notice">&#9432; NOTICE</span></c:otherwise>
                      </c:choose>
                    </td>
                    <td>
                      <a href="<%= request.getContextPath() %>/evidence?action=chain&id=${item.evidenceId}" class="btn btn-cyan btn-sm">&#8594; Chain</a>
                    </td>
                  </tr>
                </c:forEach>
              </c:otherwise>
            </c:choose>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</div>
<script src="<%= request.getContextPath() %>/js/main.js"></script>
</body>
</html>
